/*
 * This file is generated by jOOQ.
*/
package jooq.objects.routines;


import javax.annotation.Generated;

import jooq.objects.CrmSchema;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UpdateModifiedColumn extends AbstractRoutine<Object> {

    private static final long serialVersionUID = 982877116;

    /**
     * The parameter <code>crm_schema.update_modified_column.RETURN_VALUE</code>.
     */
    public static final Parameter<Object> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("trigger"), false, false);

    /**
     * Create a new routine call instance
     */
    public UpdateModifiedColumn() {
        super("update_modified_column", CrmSchema.CRM_SCHEMA, org.jooq.impl.DefaultDataType.getDefaultDataType("trigger"));

        setReturnParameter(RETURN_VALUE);
    }
}
