/*
 * This file is generated by jOOQ.
*/
package jooq.objects;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.objects.tables.Customer;
import jooq.objects.tables.User;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrmSchema extends SchemaImpl {

    private static final long serialVersionUID = -1052085331;

    /**
     * The reference instance of <code>crm_schema</code>
     */
    public static final CrmSchema CRM_SCHEMA = new CrmSchema();

    /**
     * The table <code>crm_schema.customer</code>.
     */
    public final Customer CUSTOMER = jooq.objects.tables.Customer.CUSTOMER;

    /**
     * The table <code>crm_schema.user</code>.
     */
    public final User USER = jooq.objects.tables.User.USER;

    /**
     * No further instances allowed
     */
    private CrmSchema() {
        super("crm_schema", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CUSTOMER_ID_SEQ,
            Sequences.USER_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Customer.CUSTOMER,
            User.USER);
    }
}
