/*
 * This file is generated by jOOQ.
*/
package jooq.objects;


import javax.annotation.Generated;

import jooq.objects.routines.UpdateModifiedColumn;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in crm_schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>crm_schema.update_modified_column</code>
     */
    public static Object updateModifiedColumn(Configuration configuration) {
        UpdateModifiedColumn f = new UpdateModifiedColumn();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>crm_schema.update_modified_column</code> as a field.
     */
    public static Field<Object> updateModifiedColumn() {
        UpdateModifiedColumn f = new UpdateModifiedColumn();

        return f.asField();
    }
}
