/*
 * This file is generated by jOOQ.
*/
package jooq.objects;


import javax.annotation.Generated;

import jooq.objects.tables.Customer;
import jooq.objects.tables.User;


/**
 * Convenience access to all tables in crm_schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>crm_schema.customer</code>.
     */
    public static final Customer CUSTOMER = jooq.objects.tables.Customer.CUSTOMER;

    /**
     * The table <code>crm_schema.user</code>.
     */
    public static final User USER = jooq.objects.tables.User.USER;
}
