/*
 * This file is generated by jOOQ.
*/
package jooq.objects.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1264281690;

    private Integer       id;
    private String        loginName;
    private String        role;
    private LocalDateTime created;
    private LocalDateTime modified;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.loginName = value.loginName;
        this.role = value.role;
        this.created = value.created;
        this.modified = value.modified;
    }

    public User(
        Integer       id,
        String        loginName,
        String        role,
        LocalDateTime created,
        LocalDateTime modified
    ) {
        this.id = id;
        this.loginName = loginName;
        this.role = role;
        this.created = created;
        this.modified = modified;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getLoginName() {
        return this.loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public LocalDateTime getCreated() {
        return this.created;
    }

    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    public LocalDateTime getModified() {
        return this.modified;
    }

    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(loginName);
        sb.append(", ").append(role);
        sb.append(", ").append(created);
        sb.append(", ").append(modified);

        sb.append(")");
        return sb.toString();
    }
}
